#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 001
# Feature: Keyboard-Driven Photo Selection with Export Destination Prompt

set -e

echo "========================================"
echo "Starting Flutter Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_DIR="/Users/niknoavak/Desktop/CodeProjects/SebaKolut4"

# Check Flutter is installed
if ! command -v flutter &> /dev/null; then
    echo -e "${RED}Flutter is not installed or not in PATH${NC}"
    exit 1
fi

echo -e "${GREEN}Flutter found${NC}"

# Navigate to project
cd "$PROJECT_DIR"

# Get dependencies
echo ""
echo "Installing dependencies..."
flutter pub get

if [ $? -ne 0 ]; then
    echo -e "${RED}Failed to get dependencies${NC}"
    exit 1
fi
echo -e "${GREEN}Dependencies installed${NC}"

# Run static analysis
echo ""
echo "Running static analysis..."
flutter analyze

if [ $? -ne 0 ]; then
    echo -e "${YELLOW}Static analysis found issues - check output above${NC}"
else
    echo -e "${GREEN}Static analysis passed${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: Filament Colorizer"
echo "Location: $PROJECT_DIR"
echo ""
echo "To run the app:"
echo "  flutter run -d macos    # macOS desktop"
echo "  flutter run -d windows  # Windows desktop"
echo "  flutter run -d chrome   # Web browser"
echo ""
echo "To run tests:"
echo "  flutter test"
echo ""
