#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: Undo/Redo System with Cancellable Export

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Filament Colorizer - Undo/Redo Feature"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/niknoavak/Desktop/CodeProjects/SebaKolut4"
cd "$PROJECT_DIR"

echo ""
echo "Project Directory: $PROJECT_DIR"
echo ""

# ============================================
# PREREQUISITES CHECK
# ============================================

echo "Checking prerequisites..."

# Check Flutter installation
if ! command -v flutter &> /dev/null; then
    echo -e "${RED}Flutter not found. Please install Flutter SDK.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Flutter found${NC}"

# Check Dart installation
if ! command -v dart &> /dev/null; then
    echo -e "${RED}Dart not found. Please install Dart SDK.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Dart found${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
flutter pub get

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Dependencies installed${NC}"
else
    echo -e "${RED}Failed to install dependencies${NC}"
    exit 1
fi

# ============================================
# VERIFY .ENV FILE EXISTS
# ============================================

echo ""
echo "Checking environment configuration..."

if [ ! -f ".env" ]; then
    echo -e "${YELLOW}Warning: .env file not found${NC}"
    echo "Please create .env with your GEMINI_API_KEY"
    echo "Example: GEMINI_API_KEY=your_key_here"
else
    echo -e "${GREEN}✓ .env file found${NC}"
fi

# ============================================
# RUN STATIC ANALYSIS
# ============================================

echo ""
echo "Running static analysis..."
flutter analyze

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ No analysis issues${NC}"
else
    echo -e "${YELLOW}Warning: Analysis found some issues${NC}"
fi

# ============================================
# RUN TESTS
# ============================================

echo ""
echo "Running tests..."
flutter test

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ All tests passed${NC}"
else
    echo -e "${YELLOW}Warning: Some tests failed${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "To run the app:"
echo "  flutter run -d macos    # macOS"
echo "  flutter run -d windows  # Windows"
echo "  flutter run -d chrome   # Web"
echo ""
echo "Project Structure:"
echo "  lib/providers/  - Riverpod state providers"
echo "  lib/models/     - Data models"
echo "  lib/services/   - Business logic"
echo "  lib/screens/    - UI screens"
echo "  lib/widgets/    - Reusable widgets"
echo ""
echo "Key files for this feature:"
echo "  - lib/models/app_state_snapshot.dart (to create)"
echo "  - lib/providers/undo_redo_provider.dart (to create)"
echo "  - lib/widgets/undo_redo_buttons.dart (to create)"
echo ""
